---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian-7.8
  - name: debian-8.2

suites:
  - name: default
    run_list:
      - recipe[site-backuppctypo3org::default]
    attributes:
      backuppc:
        ssl_certificate: wildcard.vagrant
  - name: monitoring
    run_list:
      - recipe[t3-base::_production]
      - recipe[site-backuppctypo3org::default]
    attributes:
      backuppc:
        ssl_certificate: wildcard.vagrant
